### ISSUE TITLE
Doesn't seem to be working

### ISSUE THREAD

**Issue by robb-j** [apexskier/DefaultBrowser#11]
Hi, I just installed from the App store. It asked about setting it as my default browser and I accepted, but now nothing is happening. I can't see the menubar icon, it isn't set as my default browser (and doesn't show in that list either) in system preferences and launching the app doesn't seem to do anything. Please help!

I'm on macOS 11.5.2

Thanks,
Rob

**Comment by apexskier** [comment]
Hey, I was missing notifications in this repo for a while, so I didn't see this.

I haven't heard of this, and don't have any initial ideas.

Can you verify the application is running from activity monitor?
