### ISSUE TITLE
Apple silicon support?

### ISSUE THREAD

**Issue by gingerbeardman** [apexskier/DefaultBrowser#14]
I just upgraded to an M1 MacBook Pro, and macOS is telling me that Default Browser is an Intel-only app. I confirmed this by downloading the latest version from the Mac App Store.

Any chance of a Universal build? 

Thanks

**Comment by gingerbeardman** [comment]
Currently running an ARM build of my own, there were some fixes needed but I chose the automatic fix methods for each one in Xcode editor.

**Comment by RCL90000** [comment]
Does it work? If so, would you mind sharing the compiled app? Thank you.

**Comment by gingerbeardman** [comment]
Sure, it worked. Let's see if @apexskier will introduce a new build before I share mine.

**Comment by apexskier** [comment]
Hey, apologies for the delay. I apparently have been on participating and mentions only notifications for this repo since 2020, so I've missed a few things.

**Comment by apexskier** [comment]
Can you try running the build from https://github.com/apexskier/DefaultBrowser/releases/tag/1.2.1-alpha.1?

**Comment by RCL90000** [comment]
Trying it now. Will report if there are issues. Thank you both!

**Comment by apexskier** [comment]
Managed to try this on my work laptop (M1) and it seems fine!

**Comment by gingerbeardman** [comment]
Works for me, too!

**Comment by gingerbeardman** [comment]
Found a problem #22
