### ISSUE TITLE
Scriptable?

### ISSUE THREAD

**Issue by jackonawalk** [apexskier/DefaultBrowser#18]
It would be awesome if this app worked with Shortcuts, AppleScript, or CLI!

**Comment by apexskier** [comment]
I'm not sure exactly what you're looking for, but there are already a few ways you can script with this. Once it's set as default, you can use the standard `open` command from the cli (e.g. `open test.html`, `open https://github.com/apexskier/DefaultBrowser/`), for example.

What other sorts of things would you be interested in?

**Comment by apexskier** [comment]
v1.3.0 now has some basic Siri shortcut support - feel free to open a discussion if you have more ideas

**Comment by jackonawalk** [comment]
This is awesome! I was looking to use this with Shortcuts and change browser based on focus mode.
