### ISSUE TITLE
No longer shows up in default browser list

### ISSUE THREAD

**Issue by gschier** [apexskier/DefaultBrowser#21]
DefaultBrowser seemed to be working fine on macOS Ventura, but now it no longer seems to be settable within the system-wide default browser option. I tried uninstalling and reinstalling, but no luck. Any advice?

Awesome app, by the way! 💯 

<img width="586" alt="image" src="https://user-images.githubusercontent.com/587576/204889001-2d3414d8-30bc-4d1e-af12-d68aacf2693c.png">

**Comment by apexskier** [comment]
Hmm... not sure what changed but I think I've fixed it in https://github.com/apexskier/DefaultBrowser/commit/0295883b799df8266ecd28f5ac5ed507dfc87343 and https://github.com/apexskier/DefaultBrowser/commit/76696a5e42e49643a40313c466cb51f31d2606b6.

<img width="254" alt="Desktop   Dock - System Settings - 2022-12-03 at 14 30 48@2x" src="https://user-images.githubusercontent.com/329222/205462981-a062b7d0-e78b-4555-9519-24ff54af2826.png">

**Comment by apexskier** [comment]
https://github.com/apexskier/DefaultBrowser/releases/tag/1.3.1

**Comment by gschier** [comment]
Nice! Thanks for the fix 👍🏻

**Comment by gingerbeardman** [comment]
Still broken for me?

**Comment by gschier** [comment]
I actually noticed this too today. It does show up as the default browser but it seems to just use the previously-selected system default browser every time.

**Comment by gingerbeardman** [comment]
Yeah, it's not working as well as the old ~1.2 version (which of course I have no backup of!)

**Comment by gschier** [comment]
It seems to be working now again on 1.3.2! 🙌

![CleanShot 2022-12-15 at 11 46 59@2x](https://user-images.githubusercontent.com/587576/207953005-70e20481-16e5-4984-8bfa-4acfbd46c4c9.png)
