### ISSUE TITLE
Last previously used browser (aka `firstRunningBrowser`) not being respected

### ISSUE THREAD

**Issue by counterleft** [apexskier/DefaultBrowser#27]
Reproduction:
1. Set the primary browser to Brave.
2. Ensure that explicit browser is off.
3. Ensure that use primary browser is off.
4. Have two running browsers: Chrome and Brave
5. Make Chrome the active window (which should make it the `firstRunningBrowser`)
6. Click on url more outside of Chrome and Brave.

Expected:
1. The url should have been opened in Chrome as it was the last previously used browser.

Actual: 
1. The url will be opened in the primary browser, Brave.

**Comment by gingerbeardman** [comment]
This also fixes #23 

Thanks!
