### ISSUE TITLE
Removing Parallels for Mac Applications results in Unknown Applications in DefaultBrowser

### ISSUE THREAD

**Issue by jchlu** [apexskier/DefaultBrowser#3]
### Removing Parallels for Mac Applications results in Unknown Applications in DefaultBrowser

Upon starting DefaultBrowser and trying to blacklist SnagIt I found references to a load of old Parallels applications presumably identifying themselves as browsers.  
I removed the app links from under `~/Applications\ (Parallels)/Windows\ Applications` and rebooted, but now they still appear in DefaultBrowser as _Unknown Application_ placeholders.  
![image placeholder](https://lh3.googleusercontent.com/-j3LNY5ldGwQ/VoFg72_xofI/AAAAAAAAQcc/nKftn9FVM7Q/s572/%25255BUNSET%25255D.png)

**Comment by apexskier** [comment]
This is going to be a system level issue. macOS itself still thinks (or still thought, this is a pretty old issue report) those are apps.
