### ISSUE TITLE
I find this amusing.

### ISSUE THREAD

**Issue by chew-z** [apexskier/DefaultBrowser#4]
<img width="1280" alt="screen shot 2016-10-31 at 06 17 37" src="https://cloud.githubusercontent.com/assets/2264679/19855692/1cdd2260-9f33-11e6-91ad-1004a838860f.png">

However I was hoping Default Browser will work and replace Browser Fairy for me. I am using Chromium, Firefox Beta and Safari. However somehow I am getting this.

<img width="1280" alt="screen shot 2016-10-31 at 06 18 17" src="https://cloud.githubusercontent.com/assets/2264679/19855732/5af708d6-9f33-11e6-809f-24aa26f508e6.png">

**Comment by apexskier** [comment]
Resolved with [version 1.1.0](https://github.com/apexskier/DefaultBrowser/releases/tag/1.1.0), which will be released to the Mac App Store when approved.

**Comment by apexskier** [comment]
could not be opened. Default Browser cannot open files in the "HTML text" format

(adding this for searchability)
