### ISSUE TITLE
Support for local .html files launched from Finder

### ISSUE THREAD

**Issue by gingerbeardman** [apexskier/DefaultBrowser#7]
## What I did
- double click local .html file in Finder

## Expected
- Default Browser should open local file in most recent browser, using `file://` url
- same behaviour as when you have a proper browser set as default

## Actual
- error

<img width="420" alt="Screen shot 2020-08-31 at 11 26 49" src="https://user-images.githubusercontent.com/49612/91710938-f3fae680-eb7c-11ea-937d-8c0d46ef6906.png">

**Comment by apexskier** [comment]
This should work, support for this was added in fe11225bedd389bb3690cf0cb405d455cd507f2e and released in version 1.1.1 (it was also reported in https://github.com/apexskier/DefaultBrowser/issues/4). What version are you running?

**Comment by gingerbeardman** [comment]
Hmm, I'm using 1.1.1

**Comment by gingerbeardman** [comment]
I think there's some crossed wires...

I am double clicking a HTML file from Finder, which gives the above error.

The support you've added I believe allows habdling of file:// links?

**Comment by gingerbeardman** [comment]
Sorry for the multiple replies.

A quick look shows that the plist would need something along the lines of:

```
<dict>
    <key>CFBundleTypeExtensions</key>
    <array>
        <string>html</string>
    </array>
</dict>
```

In fact, I modified `Info.plist` to add that and the above error went away... but nothing happened.

So the app would need to be modified to do something with the file path of the .html file that launched it.

**Comment by apexskier** [comment]
Strange - this is working for me. I'm not on the computer I develop this app on, so I'm not on a dev version or anything

<img width="272" alt="Screen Shot 2020-09-10 at 12 35 13" src="https://user-images.githubusercontent.com/329222/92718511-346b1900-f362-11ea-868b-bf01ee1a12b1.png">

![Screen Recording 2020-09-10 at 12 35 37](https://user-images.githubusercontent.com/329222/92718522-37fea000-f362-11ea-9cd1-aed144b74471.gif)

**Comment by gingerbeardman** [comment]
How odd.

I'll prod a bit more.

**Comment by gingerbeardman** [comment]
ps: I'm on Mojave

**Comment by apexskier** [comment]
I just reproduced this, not sure how though

**Comment by apexskier** [comment]
I think I have a fix in https://github.com/apexskier/DefaultBrowser/pull/9

**Comment by gingerbeardman** [comment]
Super! Thanks, I'll check it out when it hits the App Store.
